### ISSUE TITLE
what language should be used for configuration?

### ISSUE THREAD

**Issue by nirvana6** [rsvim/rsvim#128]
long time no see. Now I come here and find you have launch a fresh new project.

Congrats!

I am curious which script language should be used for configuring? I beg not to use `Lua` again.

**Comment by linrongbin16** [comment]
js/ts

**Comment by nirvana6** [comment]
> JavaScript/TypeScript will be officially supported

Good. I just pick up some knowledge of javascript.  In the end I can do something magic with neovim/rsvim.
